FROM public.ecr.aws/lambda/python:3.13

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR ${LAMBDA_TASK_ROOT}

COPY .python-version pyproject.toml uv.lock .

RUN uv pip install --system -r pyproject.toml && uv pip install --system mangum

COPY . .

RUN cat <<'EOF' > handler.py
from mangum import Mangum
from main import app

handler = Mangum(app)
EOF

CMD ["handler.handler"]
